<?xml version="1.0" encoding="utf-8"?><Database Name="SixNet_BBS" Class="BBSDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=dloczero;Initial Catalog=SixNet_BBS;Persist Security Info=True;User ID=sixnet_bbs" SettingsObjectName="SixNet_BBS_Data.Properties.Settings" SettingsPropertyName="SixNet_BBSConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AccessGroups" Member="AccessGroups">
    <Type Name="AccessGroup">
      <Column Name="AccessGroupId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccessGroupNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CallsPerDay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MinutesPerCall" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Flag_Remote_Maintenance" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Is_SysOp" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserUDBases" Member="UserUDBases">
    <Type Name="UserUDBase">
      <Column Name="UserUDBaseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UDBaseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastVisit" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="UDBase_UserUDBase" Member="UDBase" ThisKey="UDBaseId" OtherKey="UDBaseId" Type="UDBase" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="User_UserUDBase" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BBSConfigs" Member="BBSConfigs">
    <Type Name="BBSConfig">
      <Column Name="BBSConfigId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SysOpUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BBS_Name" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="BBS_URL" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="BBS_Port" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SysOp_Handle" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="SysOp_Email" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CallLogs" Member="CallLogs">
    <Type Name="CallLog">
      <Column Name="CallLogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Connected" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Disconnected" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Feedbacks" Member="Feedbacks">
    <Type Name="Feedback">
      <Column Name="FeedbackId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Body" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FromUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sent" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FileDetails" Member="FileDetails">
    <Type Name="FileDetail">
      <Column Name="FileDetailId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UDBaseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UploaderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Filename" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FileSizeInBytes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Uploaded" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="UDBase_FileDetail" Member="UDBase" ThisKey="UDBaseID" OtherKey="UDBaseId" Type="UDBase" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="User_FileDetail" Member="User" ThisKey="UploaderID" OtherKey="UserId" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GFileAreas" Member="GFileAreas">
    <Type Name="GFileArea">
      <Column Name="GFileAreaId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="LongDescription" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ParentAreaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccessLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GFileArea_GFileDetail" Member="GFileDetails" ThisKey="GFileAreaId" OtherKey="GFileAreaId" Type="GFileDetail" />
    </Type>
  </Table>
  <Table Name="dbo.GFileDetails" Member="GFileDetails">
    <Type Name="GFileDetail">
      <Column Name="GFileDetailId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GFileAreaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Filename" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DisplayFilename" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="PETSCII" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FileSizeInBytes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Added" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="GFileArea_GFileDetail" Member="GFileArea" ThisKey="GFileAreaId" OtherKey="GFileAreaId" Type="GFileArea" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Graffiti" Member="Graffitis">
    <Type Name="Graffiti">
      <Column Name="GraffitiId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Posted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MessageBaseAreas" Member="MessageBaseAreas">
    <Type Name="MessageBaseArea">
      <Column Name="MessageBaseAreaId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="LongDescription" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ParentAreaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccessLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MessageBaseArea_MessageBase" Member="MessageBases" ThisKey="MessageBaseAreaId" OtherKey="MessageBaseArea_MessageBaseAreaId" Type="MessageBase" />
    </Type>
  </Table>
  <Table Name="dbo.MessageBases" Member="MessageBases">
    <Type Name="MessageBase">
      <Column Name="MessageBaseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="LongDescription" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ParentArea" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccessLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MessageBaseArea_MessageBaseAreaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="MessageBase_MessageHeader" Member="MessageHeaders" ThisKey="MessageBaseId" OtherKey="MessageBaseId" Type="MessageHeader" />
      <Association Name="MessageBase_UserMessageBase" Member="UserMessageBases" ThisKey="MessageBaseId" OtherKey="MessageBaseId" Type="UserMessageBase" />
      <Association Name="MessageBaseArea_MessageBase" Member="MessageBaseArea" ThisKey="MessageBaseArea_MessageBaseAreaId" OtherKey="MessageBaseAreaId" Type="MessageBaseArea" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MessageBodies" Member="MessageBodies">
    <Type Name="MessageBody">
      <Column Name="MessageBodyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MessageHeaderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Body" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Association Name="MessageBody_MessageHeader" Member="MessageHeaders" ThisKey="MessageBodyId" OtherKey="MessageBody_MessageBodyId" Type="MessageHeader" />
    </Type>
  </Table>
  <Table Name="dbo.MessageHeaders" Member="MessageHeaders">
    <Type Name="MessageHeader">
      <Column Name="MessageHeaderId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MessageThreadId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MessageBaseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Anonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Posted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MessageBody_MessageBodyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MessageHeader_MessageHeaderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="MessageHeader_MessageHeader" Member="MessageHeaders" ThisKey="MessageHeaderId" OtherKey="MessageHeader_MessageHeaderId" Type="MessageHeader" />
      <Association Name="MessageBase_MessageHeader" Member="MessageBase" ThisKey="MessageBaseId" OtherKey="MessageBaseId" Type="MessageBase" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="MessageBody_MessageHeader" Member="MessageBody" ThisKey="MessageBody_MessageBodyId" OtherKey="MessageBodyId" Type="MessageBody" IsForeignKey="true" />
      <Association Name="MessageHeader_MessageHeader" Member="MessageHeader1" ThisKey="MessageHeader_MessageHeaderId" OtherKey="MessageHeaderId" Type="MessageHeader" IsForeignKey="true" />
      <Association Name="User_MessageHeader" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MessageThreads" Member="MessageThreads">
    <Type Name="MessageThread">
      <Column Name="MessageThreadId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MessageBaseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InitialMessageHeaderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.News_Item" Member="News_Items">
    <Type Name="News_Item">
      <Column Name="News_ItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Posted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Body" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PFileAreas" Member="PFileAreas">
    <Type Name="PFileArea">
      <Column Name="PFileAreaId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="LongDescription" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ParentAreaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccessLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PFileArea_PFileDetail" Member="PFileDetails" ThisKey="PFileAreaId" OtherKey="PFileArea_PFileAreaId" Type="PFileDetail" />
    </Type>
  </Table>
  <Table Name="dbo.PFileDetails" Member="PFileDetails">
    <Type Name="PFileDetail">
      <Column Name="PFileDetailId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PFileNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentAreaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Filename" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Added" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PFileArea_PFileAreaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PFileArea_PFileDetail" Member="PFileArea" ThisKey="PFileArea_PFileAreaId" OtherKey="PFileAreaId" Type="PFileArea" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SysConfigs" Member="SysConfigs">
    <Type Name="SysConfig">
      <Column Name="SysConfigId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DatabaseVersion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UDBaseAreas" Member="UDBaseAreas">
    <Type Name="UDBaseArea">
      <Column Name="UDBaseAreaId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="LongDescription" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ParentAreaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccessLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UDBases" Member="UDBases">
    <Type Name="UDBase">
      <Column Name="UDBaseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="LongDescription" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ParentArea" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccessLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="UDBase_UserUDBase" Member="UserUDBases" ThisKey="UDBaseId" OtherKey="UDBaseId" Type="UserUDBase" />
      <Association Name="UDBase_FileDetail" Member="FileDetails" ThisKey="UDBaseId" OtherKey="UDBaseID" Type="FileDetail" />
    </Type>
  </Table>
  <Table Name="dbo.UDFiles" Member="UDFiles">
    <Type Name="UDFile">
      <Column Name="UDFileId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Filename" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Uploaded" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Uploader" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Uploadername" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UDBaseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Filesize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserDefinedFields" Member="UserDefinedFields">
    <Type Name="UserDefinedField">
      <Column Name="UserDefinedFieldId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FieldValue" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserMessageBases" Member="UserMessageBases">
    <Type Name="UserMessageBase">
      <Column Name="UserMessageBaseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MessageBaseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HighestMessageRead" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MessageBase_UserMessageBase" Member="MessageBase" ThisKey="MessageBaseId" OtherKey="MessageBaseId" Type="MessageBase" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="User_UserMessageBase" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserReads" Member="UserReads">
    <Type Name="UserRead">
      <Column Name="UserReadId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MessageHeaderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HashedPassword" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LastConnection" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastDisconnection" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastConnectionIP" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AccessLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RealName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ComputerType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="User_UserUDBase" Member="UserUDBases" ThisKey="UserId" OtherKey="UserId" Type="UserUDBase" />
      <Association Name="User_FileDetail" Member="FileDetails" ThisKey="UserId" OtherKey="UploaderID" Type="FileDetail" />
      <Association Name="User_MessageHeader" Member="MessageHeaders" ThisKey="UserId" OtherKey="UserId" Type="MessageHeader" />
      <Association Name="User_UserMessageBase" Member="UserMessageBases" ThisKey="UserId" OtherKey="UserId" Type="UserMessageBase" />
    </Type>
  </Table>
</Database>